name: Continuous integration
#on: [pull_request, push]
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  KhiCAS:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -C apps/KhiCAS cleanall
      - run: make KhiCAS_rebuild
      - run: ./tool/archive KhiCAS.tar KhiCAS
      - uses: actions/upload-artifact@master
        with:
          name: KhiCAS
          path: KhiCAS.tar
  BadApple:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make BadApple_rebuild
      - run: ./tool/archive BadApple.tar BadApple
      - uses: actions/upload-artifact@master
        with:
          name: BadApple
          path: BadApple.tar
  CHIP-8:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make CHIP-8_rebuild
      - run: ./tool/archive CHIP-8.tar CHIP-8
      - uses: actions/upload-artifact@master
        with:
          name: CHIP-8
          path: CHIP-8.tar
  Example:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make Example_rebuild
      - run: ./tool/archive Example.tar Example
      - uses: actions/upload-artifact@master
        with:
          name: Example
          path: Example.tar
  Example-Cpp:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make Example-Cpp_rebuild
      - run: ./tool/archive Example-Cpp.tar Example-Cpp
      - uses: actions/upload-artifact@master
        with:
          name: Example-Cpp
          path: Example-Cpp.tar
  HexEdit:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make HexEdit_rebuild
      - run: ./tool/archive HexEdit.tar HexEdit
      - uses: actions/upload-artifact@master
        with:
          name: HexEdit
          path: HexEdit.tar
  Nofrendo:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make Nofrendo_rebuild
      - run: ./tool/archive Nofrendo.tar Nofrendo
      - uses: actions/upload-artifact@master
        with:
          name: Nofrendo
          path: Nofrendo.tar
  Peanut-GB:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make Peanut-GB_rebuild
      - run: ./tool/archive Peanut-GB.tar Peanut-GB
      - uses: actions/upload-artifact@master
        with:
          name: Peanut-GB
          path: Peanut-GB.tar
  Periodic:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make Periodic_rebuild
      - run: ./tool/archive Periodic.tar Periodic
      - uses: actions/upload-artifact@master
        with:
          name: Periodic
          path: Periodic.tar
  UnitCircle:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install wget gdb gcc g++ libgmp-dev libmpfr-dev libmpfi-dev libpari-dev libgsl0-dev libxext-dev libpng-dev libjpeg-dev libreadline-dev libncurses5-dev mesa-common-dev libx11-dev libxt-dev libxft-dev libntl-dev libgl1-mesa-dev libgl-dev libao-dev hevea debhelper libfltk1.3-dev build-essential git imagemagick libx11-dev libxext-dev libfreetype6-dev libpng-dev libjpeg-dev pkg-config gcc-arm-none-eabi binutils-arm-none-eabi dfu-util texinfo autoconf-archive -y

      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make UnitCircle_rebuild
      - run: ./tool/archive UnitCircle.tar UnitCircle
      - uses: actions/upload-artifact@master
        with:
          name: UnitCircle
          path: UnitCircle.tar

env:
  ACCEPT_OFFICIAL_TOS: 1